name: PubDigest
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.9
  - pandas=1.3.4
  - openpyxl
  - matplotlib=3.3.1
  - seaborn=0.11.0
  - numpy=1.19.2
  - gensim=3.8.0
  - scikit-learn=0.23.2
  - scipy=1.7.1
  - requests
  - pip
  - pip:
    - chembl-webresource-client==0.10.7
    - nltk==3.5
    - jupyterlab
    - tqdm
    - unidecode
    - wordcloud
    - pyyaml
    - pyenchant
    - pymed @ git+https://github.com/dansteiert/pymed