# Affiliation Matching:
# mapping of used country names to their reference in our country list e.g. non-english spellings
country_dict:
  uk: United Kingdom
  us: United States
  usa: United States
  united states of america: United States
  espana: Spain
  the netherlands: Netherlands
  czech republic: Czechia
  korea: South Korea
  slovak republic: Slovakia
  republic of korea: South Korea
  polan: Poland
  peoples republic of china: China
  pr china: China
  georgia: United States
  democratic people's republic of korea: North Korea
  alabama: United States
  alaska: United States
  arizona: United States
  arkansas: United States
  california: United States
  colorado: United States
  connecticut: United States
  delaware: United States
  florida: United States
  georgia: United States
  hawaii: United States
  idaho: United States
  illinois: United States
  indiana: United States
  iowa: United States
  kansas: United States
  kentucky: United States
  louisiana: United States
  maine: United States
  maryland: United States
  massachusetts: United States
  michigan: United States
  minnesota: United States
  mississippi: United States
  missouri: United States
  montana: United States
  nebraska: United States
  nevada: United States
  new hampshire: United States
  new jersey: United States
  new mexico: United States
  new york: United States
  north carolina: United States
  north dakota: United States
  ohio: United States
  oklahoma: United States
  oregon: United States
  pennsylvania: United States
  rhode Island: United States
  south carolina: United States
  south dakota: United States
  tennessee: United States
  texas: United States
  utah: United States
  vermont: United States
  virginia: United States
  washington: United States
  west virginia: United States
  wisconsin: United States
  wyoming: United States




# mapping of used city names to their reference in our city list e.g. non-english spellings
city_dict:
  lisboa: Lisbon
  la jolla: San Diego
  le plessis robinson: Paris
  le plessis: Paris
  robinson: Paris
  le kremlin: Paris
  bicetre: Paris
  hanover: Hannover
  clayton: Melbourne
  praha: Prague
  afyon: Afyonkarahisar
  petersburg: Saint Petersburg
  muenster: Munster
  tel hashomer: Ramat Gan
  nauheim: Bad Nauheim
  etienne: Saint-Etienne
  geneve: Geneva
  quebec: Quebec City # might lead to wrongly placed institutes quebec is the state
  xian: Xi'an
  kitakyushu: Nakama # not accurate (is an independent city next by), since not in DB
  washington dc: Washington
  miki: Takamatsu
  newcastle upon thyne: Newcastle
  torino: Turin
  vimercate: Milan
  pairs-est: Paris
  ho chi minh: Ho Chi Minh City



# mapping of used institute names to their reference in our institute list
institute_names: ["Institute", "Center", "University", "Clinic", "Hospital", "College", "School"]
