# System setup
working_dir: null # if null, the current working directory is used

processors: 6 #  leave a processor free for OS if running on a PC
dataset_compile_batch_size: 10000


logging:
  logger_name: "PubDigest"
  format: '[%(levelname)s] [%(asctime)s] (%(filename)s:%(lineno)d) - %(message)s'
  filename: "log_file.log"
  level: "INFO"

logging_console: True